setup project
Bornittah/football-leagues pull request #1
Opened 2022-06-27 13:44 UTC by Bornittah

2022-06-30 21:43 UTC, AnselemOdims requested changes
### Hi @Bornittah , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please record a presentation video of no more than 5mins in length explaining the features of the project and highlighting a piece of code you are most proud of.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-30 21:43 UTC, AnselemOdims commented on src/modules/user-interactions.js
> +};
- [ ] Good job working on this, but the comments on the modal popup does not get fetched when the modal opens not until a new comment is made. Please kindly ensure that the comments get loaded and displayed when the modal is popped up

2022-06-30 21:43 UTC, AnselemOdims commented on src/modules/app.test.js
> +  });
- [ ] You are expected to create a function to calculate counter numbers on each page(Home and comments). This function is what you are going to write tests for. Please kindly create the function and write tests for it.

2022-07-01 12:00 UTC, KDlamini approved these changes
### Hi @Bornittah 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!🎊 🥳 

## Highlights 🌞 
✔️  Good PR title and description
✔️  Good UI and wireframe parsing
✔️  API integration implemented properly
✔️  ES6 and modules are used correctly
✔️  Commit messages are meaningful
✔️  No linter errors

# Status: Approved ✔️ 

![giphyapproved](https://user-images.githubusercontent.com/38088818/152676874-3b2edc2c-a46f-4da6-b253-be859d2a2c65.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 12:16 UTC, merged